---
title: "Untitled"
output: html_document
---

This codebook is to define and describe variables in the dataset "TidyData.txt", the result of running "run_analysis.R"

The starting data can be found : https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip
A description of the starting data :  http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

A summary of the "TidyData.txt" is as follows:
It contains 180 observations with 68 variables. 

There are 30 subjects and 6 activities, giving 180 observations
There are 68 variables, 66 associated with the values (33 means and 33 standard deviations), with subjectID and Activity
The first row contains the names for each column. 

### Activities
1. Laying
2. Sitting
3. Standing
4. Walking
5. Walking_downstairs
6. Walking_upstairs

### Measurements
*XYZ indicate directions (dimensions).

* tBodyAcc-XYZ
* tGravityAcc-XYZ
* tBodyAccJerk-XYZ
* tBodyGyro-XYZ
* tBodyGyroJerk-XYZ
* tBodyAccMag
* tGravityAccMag
* tBodyAccJerkMag
* tBodyGyroMag
* tBodyGyroJerkMag
* fBodyAcc-XYZ
* fBodyAccJerk-XYZ
* fBodyGyro-XYZ
* fBodyAccMag
* fBodyAccJerkMag
* fBodyGyroMag
* fBodyGyroJerkMag

### Descriptive variable names
* leading t or f is based on time or frequency measurements.
* Body = related to body movement.
* Gravity = acceleration of gravity
* Acc = accelerometer measurement
* Gyro = gyroscopic measurements
* Jerk = sudden movement acceleration
* Mag = magnitude of movement
* mean and SD are calculated for each subject for each activity for each mean and SD measurements. The units given are g’s for the * * * * accelerometer and rad/sec for the gyro and g/sec and rad/sec/sec for the corresponding jerks.
